spring:
  application:
  name: employee
  data:
    mongodb:
      uri: mongodb://localhost:27017/employee?authSource=admin&retryWrites=true&w=majority
server:
  port: 9099

logging:
  level :
    root : DEBUG